apiVersion: v2
name: javaapp
description: A Helm chart for deploying a sample application
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: mysql
    version: 1.0.0
    repository: https://example.com/charts
maintainers:
  - name: Your Name
    email: your.email@example.com
